### PR TITLE
Custom Job Tags

### LINKED ISSUE #10: Add ability to add custom tags
Maybe i missed it but would it be possible to allow adding additional tags for horizon and monitoring the queueable actions?

### PR DESCRIPTION
**Pull request by nathanheffley**
This would resolve #10 by adding the ability to specify custom tags that would be applied to the action and show up in Horizon. By using a Queueable Action's `tags()` function it gives the developer the ability to implement tags exactly how they would on a regular job, even tags with dynamic values based on the queuable action's parameters.

Setting custom tags won't work as it's implemented here if the developer creates an `ActionJob` using a class name instead of an actual action model. Unfortunately, I couldn't come up with a clean solution for implementing this functionality when just the class name was provided. But because there isn't actually any documentation around using the class name that it would be better to keep this as simple as possible and just support the official methodology.

I know you're trying to keep this package as light as possible, but being able to set the tags would be extremely useful for projects that use lots of actions and runs them often. Since you're already supporting Horizon tags, I think it makes sense to allow that to be configurable. Currently, it's pretty difficult to find the action I'm looking for if I don't know exactly when it occurred. This functionality would allow me to tag actions based on what User they were related to and see everything that is happening on specific accounts, a significant time-saver when debugging.

### CODE REVIEW

**Comment by nathanheffley** [comment]
Hmmm, it looks something isn't quite right with the TravisCI config. The tests for Laravel 5.8.* are passing just fine but the Carbon dependency is causing the `--prefer-lowest` tests to fail 😞

**Comment by herpaderpaldent** [comment]
Hey @nathanheffley 
i just checked back and see you have a PR open to add custom tagging. Great 👍  thank you. I hope it get merged soon. 
Regarding the failed test on travis, well it fails for other recently merged PRs too: https://travis-ci.org/spatie/laravel-queueable-action/builds/578280717?utm_source=github_status&utm_medium=notification 
I wouldn't assume that it would be an issue

**Comment by heikokrebs** [comment]
Would like to have this!

**Comment by herpaderpaldent** [comment]
bump?

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
