### PR TITLE
Add support for job middleware

### PR DESCRIPTION
**Pull request by rubenvanassche**
This PR adds support for job middlewares, there's only one problem. In regular jobs we use the constructor to pass in the most important information like an `Invoice` for example. The `handle` method is used for dependencies.

In queueable actions this is reversed, the constructor receives dependencies and the `execute` method the information needed for executing the action.

The implication from this is that we cannot use information passed through the `execute` method to construct a middleware in the `middleware` method of the action. We could add `getParameters` to the `ActionJob` so we can use the `parameters` passed to the `execute` method of the action in our job middleware. But maybe that's bringing us too far from the original plan ....

Job middleware like the Ratelimeted(https://laravel.com/docs/7.x/queues#job-middleware) that don't require information about what was passed through the `execute` method of the action will off course work fine.

### CODE REVIEW

**Comment by brendt** [comment]
Looking good!

**Comment by huubvdw** [comment]
@brendt Any particular reason why this hasn't been merged? 
This would be really handy for queued actions that for example requires rate limiting.

**Comment by rubenvanassche** [comment]
@brendt Should I fix the conflicts and merge this?  Totally forgo this PR actually 😄

**Comment by brendt** [comment]
@rubenvanassche yeah go ahead!

**Comment by freekmurze** [comment]
@rubenvanassche seems like the tests are failing. Could you take a look at that?

**Comment by rubenvanassche** [comment]
Merged!

**Pull request merged**
