### PR TITLE
Support for adding Invokeable actions

### PR DESCRIPTION
**Pull request by einar-johan**
This pull request adds support for adding actions to the queue that uses the __invoke() method.

It basically checks if a property exists on the Action class (that you want to queue) that is called 'queueMethod'. If the property exists, the ActionJob class will be set to run that method, instead of the "execute" method. 

I've also added a new trait the is called "QueueableInvokeableAction" which uses the "QueueableAction" and has the 'queueMethod' set to '__invoke'. 

I believe this is a nice new feature as your "Laravel Beyond CRUD" has multiple examples with actions that use the invoke method :)

### CODE REVIEW

**Comment by brendt** [comment]
Nice one! Could you also update the README within this PR and list this feature?

**Comment by einar-johan** [comment]
Alright. Sorry about that, I have now made some updates to the readme file.

Hope you don't mind that SublimeText went a little crazy with cleaning up some whitespaces at the end of a couple of the lines.

Do you think it should be mentioned that you could set the $queueMethod property if you are executing the actions through other method names, like for example "handle"? My guess is that  99% of the users are covered with the two traits that are provided now, so I decided to not mention it. I'll add it if you want.

**Comment by brendt** [comment]
One more thought: couldn't we determine whether `execute` or `__invoke` should be used right in the `QueuableAction` trait instead of having a separate one? What if we'd implement queueMethod like so?

```php
protected function queueMethod(): string
{
    if (method_exists($this, '__invoke')) {
        return '__invoke';
    }

    return 'execute';
}
```

You could still override that method in the action itself, and you wouldn't need two traits. win-win, no?

**Comment by einar-johan** [comment]
Brilliant. Thats a better idea. 

The branch is updated with this change. I added it to the trait as you suggested ;) I guess the method also could be added to the `ActionJob` class. 

Readme and everything else should be updated to work with this change.

**Comment by brendt** [comment]
Great! Let's merge and tag this :)

**Comment by brendt** [comment]
Here we go! https://github.com/spatie/laravel-queueable-action/releases/tag/2.8.0

**Comment by einar-hansen** [comment]
Great ;)

**Pull request merged**
